name: Deploy to Firebase #name of the workflow
on: #events on which the job is triggered
  workflow_dispatch:
    inputs:
      release_notes:
        type: string
        required: true
        default: 'Manual Debug Build'

jobs: #tasks you command github actions to execute through yaml file --series of steps that are usually executed sequentially on the same runner
  build: #create a build
    name: Building and distributing app
    runs-on : ubuntu-latest #runner is the remote computer that GitHub Actions uses to execute the jobs you tell it to.
    steps: #actions perform while executing above job
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: Setup Java JDK
        uses: actions/setup-java@v4.0.0
        with:
          java-version: '18'
          distribution: 'adopt'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Change wrapper permissions
        run: chmod +x ./gradlew

      - name: Execute Gradle command -- assemble debug
        run: ./gradlew assembleDebug

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.3
        with:
          name: AndroidCICD.apk
          path: app/build/outputs/apk/debug/app-debug.apk

      - name: Upload artifact to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{secrets.FIREBASE_APP_ID}}
          serviceCredentialsFileContent: ${{ secrets.CREDENTIAL_FILE_CONTENT }}
          groups: testers
          file: app/build/outputs/apk/debug/app-debug.apk




