name: SonarQube Test #name of the workflow
on: #events on which the job is triggered
  workflow_dispatch:
    inputs:
      release_notes:
        type: string
        required: true
        default: 'Manual Debug Build'

jobs:
  build:
    runs-on:
      - ubuntu-latest
    steps:
      - name: Check out Git Repository
        uses: actions/checkout@v3

      - name: set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Gradle Clean
        run: ./gradlew clean

      - name: Gradle Lint
        run: ./gradlew lint

      - name: Gradle Build and generating apk files
        run: ./gradlew build

      - name: Code Coverage test - Jacoco
        run: ./gradlew jacocoTest

      - name: Cache SonarQube packages
        uses: actions/cache@v1
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar


      - name: Cache Gradle packages
        uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle

      - name: Code Scan Analysis - SonarQube
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        run: ./gradlew sonarqube -Dsonar.projectKey=AndroidCICD